import differential_invariants_local_theory_geometric_theorem_canonical_lane_mathlib.GateLemmas
namespace HautevilleHouse
namespace differential_invariants_local_theory_geometric_theorem_canonical_lane_mathlib
structure ConstrainedTheoremClosure where
  admissible :: intro :: constraint :: consequence :: proof ::
theorem canonical : ConstrainedTheoremClosure :=
  ConstrainedTheoremClosure.intro
end differential_invariants_local_theory_geometric_theorem_canonical_lane_mathlib
end HautevilleHouse
